language: android
sudo: required


android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-25

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data


before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK=$HOME/android-ndk-root

install:
  - sudo apt-get install build-essential

script: python build.py --android 25 --native


before_deploy:
  - export RELEASE_FILES=$(ls */install/*.deb */bin/* */lib/*.so | tr '\n' ' ')
  - echo "deploying $RELEASE_FILES to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file:  "build/build/pack/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
