language: cpp
sudo: required
dist: trusty

compiler:
- gcc

#before_install:
#- sudo apt-get update -qq

#install:

script: ./build.py --android 25 --native


before_deploy:
  - export RELEASE_FILES=$(ls */install/*.deb */bin/* */lib/*.so | tr '\n' ' ')
  - echo "deploying $RELEASE_FILES to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file:  "build/build/pack/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
