language: android
sudo: required
dist: trusty


android:
  components:
    - tools
    - platform-tools
    - android-25

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK=$HOME/android-ndk-root

install:
  - sudo apt-get install build-essential

script: python build.py --android 25 --native


before_deploy:
  - export RELEASE_FILES=$(ls */install/*.deb */bin/* */lib/*.so | tr '\n' ' ')
  - echo "deploying $RELEASE_FILES to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file:  "build/build/pack/*"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
