
# Set output directories
function(setOutDir BIN LIB ARCH)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/${BIN}     PARENT_SCOPE)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/${LIB}     PARENT_SCOPE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/${ARCH}    PARENT_SCOPE)
endfunction(setOutDir)


# cpack
function(setupCPack)
    if(UNIX)
        SET(CPACK_GENERATOR "DEB"                                       PARENT_SCOPE)
        SET(CPACK_DEBIAN_PACKAGE_MAINTAINER ${META_PROJECT_AUTHOR}      PARENT_SCOPE)
    endif()

    set(CPACK_COMPONENTS_ALL                ${INSTALL_COMPONENTS}       PARENT_SCOPE)
    set(CPACK_PACKAGE_NAME                  ${META_PROJECT_NAME}        PARENT_SCOPE)
    set(CPACK_PACKAGE_VENDOR                ""                          PARENT_SCOPE)
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY   ${META_PROJECT_DESCRIPTION} PARENT_SCOPE)
    set(CPACK_PACKAGE_VERSION               ${META_VERSION}             PARENT_SCOPE)
    set(CPACK_PACKAGE_VERSION_MAJOR         ${META_VERSION_MAJOR}       PARENT_SCOPE)
    set(CPACK_PACKAGE_VERSION_MINOR         ${META_VERSION_MINOR}       PARENT_SCOPE)
    set(CPACK_PACKAGE_VERSION_PATCH         ${META_VERSION_PATCH}       PARENT_SCOPE)
    set(CPACK_PACKAGE_INSTALL_DIRECTORY     ${META_PROJECT_NAME}        PARENT_SCOPE)

    include(CPack)
endfunction(setupCPack)