
# Set output directories
function(setOutupDir PATH_RELATIV)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}${PATH_RELATIV})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}${PATH_RELATIV})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}${PATH_RELATIV})
endfunction(setOutupDir)