
# Set output directories
function(setOutDir PATH_RELATIV)
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/${PATH_RELATIV} PARENT_SCOPE)
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/${PATH_RELATIV} PARENT_SCOPE)
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/${PATH_RELATIV} PARENT_SCOPE)
endfunction(setOutDir)